# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-08 07:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('image_url', models.CharField(max_length=100)),
                ('batch', models.CharField(max_length=10)),
            ],
        ),
    ]
