# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-08 07:38
from __future__ import unicode_literals

import Faculty.models
import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseId', models.CharField(max_length=5, validators=[django.core.validators.MinLengthValidator(5)])),
                ('courseName', models.CharField(max_length=20)),
                ('batch', models.IntegerField(default=2013, validators=[Faculty.models.validate_batch])),
            ],
        ),
        migrations.CreateModel(
            name='FacultyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('department', models.CharField(choices=[('CS', 'Computer Science'), ('IT', 'Information Technology')], default='IT', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.DateTimeField(default=datetime.datetime.now)),
                ('endDate', models.DateTimeField()),
                ('hashString', models.IntegerField()),
                ('lateSubmission', models.BooleanField(default=True)),
                ('lateSubmissionPeriod', models.IntegerField(blank=True, validators=[Faculty.models.validate_late_submission], verbose_name='Late submission period (in minutes)')),
                ('reviewType', models.IntegerField(choices=[(0, 'Email'), (1, 'Zip/Tar archive'), (2, 'API Endpoint')], default=1)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Faculty.Course')),
            ],
        ),
        migrations.CreateModel(
            name='TitleFormat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleName', models.CharField(max_length=20)),
                ('instituteId', models.BooleanField(default=False)),
                ('groupId', models.BooleanField(default=True)),
                ('groupInitial', models.CharField(blank=True, max_length=20)),
                ('courseCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Faculty.Course')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Faculty.FacultyModel'),
        ),
    ]
